language: node_js
dist: trusty
sudo: required
node_js:
  - "7"
notifications:
  email: false
deploy:
  app: event-portal-backend
  provider: heroku
  api_key:
    secure: *key*
  on:
    tags: true  

before_install:
  - npm i touch@latest
  - npm i bcrypt --save
